name: usercentrics_manager
description: A helper package to manage user-centric privacy and compliance across platforms.
version: 0.0.1
homepage: https://www.utanium.org/usercenteric_manager

environment:
  sdk: ">=3.0.0 <4.0.0" # Adjust based on your current required Dart version
  flutter: ">=3.10.0" # Adjust based on your current required Flutter version

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.3.0
  usercentrics_sdk: ^2.24.1
  # Add any other core dependencies needed for the package here (e.g., http, path)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
